### ISSUE TITLE
HOW WE CAN A=INSTALL ASSISTANT MANAGER 

### ISSUE THREAD

**Issue by shobhitagnihotri69** [MrXandbadas/MrX_OAI_Assistant_Manager#14]

**Comment by MrXandbadas** [comment]
I dont quite understand the question

**Comment by shobhitagnihotri69** [comment]
When I'm running that file your have provide in assistant manager folder it is is showing this error

**Comment by MrXandbadas** [comment]
Please ensure you are using the MAIN branch of the repo!
I am on my Mac and can no find any issues that you are experiencing currently. 
Other than Git not being a package available (just removed it from the 'Dynamic_functions.py" file for my local instance)
